from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(816, 685)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(140, 8, 491, 71))
        font = QtGui.QFont()
        font.setFamily("Andalus")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 71, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 105, 71, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 130, 71, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 155, 54, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 180, 71, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 205, 54, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 230, 54, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(20, 255, 54, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(20, 280, 71, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(20, 305, 71, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(20, 330, 71, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.product_type = QtWidgets.QLineEdit(self.centralwidget)
        self.product_type.setGeometry(QtCore.QRect(120, 80, 400, 20))
        self.product_type.setObjectName("product_type")
        self.board_type = QtWidgets.QLineEdit(self.centralwidget)
        self.board_type.setGeometry(QtCore.QRect(120, 105, 400, 20))
        self.board_type.setObjectName("board_type")
        self.product_model = QtWidgets.QLineEdit(self.centralwidget)
        self.product_model.setGeometry(QtCore.QRect(120, 130, 400, 20))
        self.product_model.setObjectName("product_model")
        self.serial_number = QtWidgets.QLineEdit(self.centralwidget)
        self.serial_number.setGeometry(QtCore.QRect(120, 155, 400, 20))
        self.serial_number.setObjectName("serial_number")
        self.file_number = QtWidgets.QLineEdit(self.centralwidget)
        self.file_number.setGeometry(QtCore.QRect(120, 180, 400, 20))
        self.file_number.setObjectName("file_number")
        self.date = QtWidgets.QLineEdit(self.centralwidget)
        self.date.setGeometry(QtCore.QRect(120, 205, 400, 20))
        self.date.setObjectName("date")
        self.time = QtWidgets.QLineEdit(self.centralwidget)
        self.time.setGeometry(QtCore.QRect(120, 230, 400, 20))
        self.time.setObjectName("time")
        self.operator_name = QtWidgets.QLineEdit(self.centralwidget)
        self.operator_name.setGeometry(QtCore.QRect(120, 255, 400, 20))
        self.operator_name.setObjectName("operator_name")
        self.test_time = QtWidgets.QLineEdit(self.centralwidget)
        self.test_time.setGeometry(QtCore.QRect(120, 280, 400, 20))
        self.test_time.setObjectName("test_time")
        self.test_result = QtWidgets.QLineEdit(self.centralwidget)
        self.test_result.setGeometry(QtCore.QRect(120, 305, 400, 20))
        self.test_result.setObjectName("test_result")
        self.failed_item = QtWidgets.QLineEdit(self.centralwidget)
        self.failed_item.setGeometry(QtCore.QRect(120, 330, 400, 20))
        self.failed_item.setObjectName("failed_item")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 370, 791, 241))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(6, item)
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(20, 620, 71, 20))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(11)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.select_file = QtWidgets.QLineEdit(self.centralwidget)
        self.select_file.setGeometry(QtCore.QRect(120, 620, 400, 20))
        self.select_file.setObjectName("select_file")
        self.submit_but = QtWidgets.QPushButton(self.centralwidget)
        self.submit_but.setGeometry(QtCore.QRect(550, 620, 75, 23))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.submit_but.setFont(font)
        self.submit_but.setObjectName("submit_but")
        self.modify_but = QtWidgets.QPushButton(self.centralwidget)
        self.modify_but.setGeometry(QtCore.QRect(690, 620, 75, 23))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(12)
        self.modify_but.setFont(font)
        self.modify_but.setObjectName("modify_but")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "DC110V输入板卡（DI）测试报告"))
        self.label_2.setText(_translate("MainWindow", "产品类型"))
        self.label_3.setText(_translate("MainWindow", "板卡类型"))
        self.label_4.setText(_translate("MainWindow", "产品型号"))
        self.label_5.setText(_translate("MainWindow", "序列号"))
        self.label_6.setText(_translate("MainWindow", "文件编号"))
        self.label_7.setText(_translate("MainWindow", "日期"))
        self.label_8.setText(_translate("MainWindow", "时间"))
        self.label_9.setText(_translate("MainWindow", "操作员"))
        self.label_10.setText(_translate("MainWindow", "测试用时"))
        self.label_11.setText(_translate("MainWindow", "测试结果"))
        self.label_12.setText(_translate("MainWindow", "不合格项"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1供电测试"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "所有通道为On"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "2通道测试"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "全输出"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "半输出1"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "半输出2"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "全关闭"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "测试项名称"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "单位"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "最小值"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "最大值"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "比较方式"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "测量值"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "结果"))
        self.label_13.setText(_translate("MainWindow", "选择文件"))
        self.submit_but.setText(_translate("MainWindow", "确认"))
        self.modify_but.setText(_translate("MainWindow", "提交修改"))

