# Generated by Django 2.1 on 2018-12-20 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ip',
            name='device',
            field=models.ForeignKey(help_text='所在网卡', on_delete=None, to='servers.NetworkDevice', verbose_name='所在网卡'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='host',
            field=models.ForeignKey(help_text='所在服务器', on_delete=None, to='servers.Server', verbose_name='所在服务器'),
        ),
        migrations.AlterField(
            model_name='server',
            name='cabinet',
            field=models.ForeignKey(help_text='所在机柜', null=True, on_delete=None, to='cabinet.Cabinet', verbose_name='所在机柜'),
        ),
        migrations.AlterField(
            model_name='server',
            name='idc',
            field=models.ForeignKey(help_text='所在机房', null=True, on_delete=None, to='idcs.Idc', verbose_name='所在机房'),
        ),
        migrations.AlterField(
            model_name='server',
            name='manufacturer',
            field=models.ForeignKey(help_text='制造商', on_delete=None, to='manufacturer.Manufacturer', verbose_name='制造商'),
        ),
        migrations.AlterField(
            model_name='server',
            name='model_name',
            field=models.ForeignKey(help_text='服务型号', on_delete=None, to='manufacturer.ProductModel', verbose_name='服务型号'),
        ),
    ]
